### ISSUE TITLE
Log Files cannot be retrieved

### ISSUE THREAD

**Issue by ButKor** [thin-edge/tedge-demo-container#16] opened 2023-05-09 17:35 UTC
I am trying to get Log Files on the Parent-/Main Device. The operation is picked up but immediately fails with:
`FailureReason: Handling of operation failed with No such file or directory for log type: software-management`. This is the case for all four log types: apt-terminal-log, dpkg, shell, software-management.

To produce some log content, I've also installed some software and sent some shell commands - but didn't help, same failure reason as above.

**Comment by reubenmiller** [comment] 2023-05-09 19:43
Thanks @ButKor for registering the bug, there was indeed a problem with the configured log file locations for the following log types:

* software-management
* shell

Though the other log types did work (e.g. `apt-terminal-log` and `dpkg`).

The root cause was some mismatch in log file configuration between the log path in the `tedge.toml` and the `c8y-log-plugin.toml`. I switched to use the default log paths in the `tedge.toml` so that the demo container behaves in a similar way when installing thin-edge manually on a device. I also added some integration tests to prevent this from happening in the future.

It is fixed in the latest release: [20230509.2](https://github.com/thin-edge/tedge-demo-container/releases/tag/20230509.2)

**Closed by reubenmiller** 2023-05-09 19:43 UTC
